### ISSUE TITLE
Allow generic SeisBench models

### ISSUE THREAD

**Issue by yetinam** [pyrocko/qseek#10]
Currently, the image function is only implemented for PhaseNet. However, as all pickers in SeisBench have the same interface, it would also work for the others, e.g., EQTransformer. I'd suggest modifying https://github.com/pyrocko/lassie-v2/blob/main/lassie/images/phase_net.py to accept any SeisBench model. Further advantage would be that future models added to SeisBench will automatically work with Lassie v2.

**Comment by miili** [comment]
Yes, that sounds reasonable!

**Comment by miili** [comment]
Done
