### ISSUE TITLE
Error performing qseak search

### ISSUE THREAD

**Issue by Donavin97** [pyrocko/qseek#17]
Good day.
I am trying to run qseek using python3.10 on ubuntu22.04(LTS).
I run the following command:
qseek search test.json
There is an error in the search that states: the phase: "constant:S" cannot be used, because there is no ray tracer available for the phase.
How do I fix this issue?
Thanks.
Kind regards
PS: Both Pyrocko and Qseek are installed in the same environment.

**Comment by miili** [comment]
Hi there,
the config is templated with two ray tracers, constant velocity and one for layered models.
You have to map the IDs of PhaseNet annotation (P and S) to the according ray tracer.

Check the config again and adjust names in the PhaseNet module and the traveltime provider to match.

We will update the error message to be more descriptive.

Best,

M
